export const AUTH_LOG_IN = 'AUTH_LOG_IN';
export const AUTH_LOG_OUT = 'AUTH_LOG_OUT';
export const GET_USER_DATA = 'GET_USER_DATA';
export const GET_USER_ADDRESSES = 'GET_USER_ADDRESSES';
export const GET_USER_CART = 'GET_USER_CART';
export const GET_USER_ORDERHISTORY = 'GET_USER_ORDERHISTORY';
